# Generated by Django 5.2 on 2025-06-25 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique du template', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nom du template', max_length=100)),
                ('title_template', models.CharField(help_text='Template du titre avec des variables {variable}', max_length=200)),
                ('message_template', models.TextField(help_text='Template du message avec des variables {variable}')),
                ('default_type', models.CharField(choices=[('FORMULAIRE_SOUMIS', 'Formulaire de collecte soumis'), ('FORMULAIRE_APPROUVE', 'Formulaire de collecte approuvé'), ('FORMULAIRE_REJETE', 'Formulaire de collecte rejeté'), ('COLLECTE_PLANIFIEE', 'Collecte planifiée'), ('COLLECTE_EN_COURS', 'Collecte en cours'), ('COLLECTE_TERMINEE', 'Collecte terminée'), ('COLLECTE_ANNULEE', 'Collecte annulée'), ('TRANSPORT_ASSIGNE', 'Transport assigné'), ('TRANSPORT_EN_COURS', 'Transport en cours'), ('TRANSPORT_LIVRE', 'Transport livré'), ('TRAITEMENT_COMMENCE', 'Traitement commencé'), ('TRAITEMENT_TERMINE', 'Traitement terminé'), ('RAPPORT_DISPONIBLE', 'Rapport disponible'), ('NOUVEAU_UTILISATEUR', 'Nouvel utilisateur enregistré'), ('MISE_A_JOUR', 'Mise à jour système'), ('ALERTE', 'Alerte système')], help_text='Type de notification par défaut', max_length=30)),
                ('default_priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', help_text='Priorité par défaut', max_length=10)),
                ('target_roles', models.JSONField(default=list, help_text='Liste des rôles concernés par ce type de notification')),
                ('is_active', models.BooleanField(default=True, help_text='Template actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notifications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FORMULAIRE_SOUMIS', 'Formulaire de collecte soumis'), ('FORMULAIRE_APPROUVE', 'Formulaire de collecte approuvé'), ('FORMULAIRE_REJETE', 'Formulaire de collecte rejeté'), ('COLLECTE_PLANIFIEE', 'Collecte planifiée'), ('COLLECTE_EN_COURS', 'Collecte en cours'), ('COLLECTE_TERMINEE', 'Collecte terminée'), ('COLLECTE_ANNULEE', 'Collecte annulée'), ('TRANSPORT_ASSIGNE', 'Transport assigné'), ('TRANSPORT_EN_COURS', 'Transport en cours'), ('TRANSPORT_LIVRE', 'Transport livré'), ('TRAITEMENT_COMMENCE', 'Traitement commencé'), ('TRAITEMENT_TERMINE', 'Traitement terminé'), ('RAPPORT_DISPONIBLE', 'Rapport disponible'), ('NOUVEAU_UTILISATEUR', 'Nouvel utilisateur enregistré'), ('MISE_A_JOUR', 'Mise à jour système'), ('ALERTE', 'Alerte système')], help_text='Type de notification', max_length=30)),
                ('title', models.CharField(help_text='Titre de la notification', max_length=200)),
                ('message', models.TextField(help_text='Message détaillé de la notification')),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', help_text='Niveau de priorité', max_length=10)),
                ('is_read', models.BooleanField(default=False, help_text='Indique si la notification a été lue')),
                ('action_url', models.URLField(blank=True, help_text='URL vers laquelle rediriger en cliquant sur la notification', null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Données supplémentaires liées à la notification', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date et heure de création')),
                ('read_at', models.DateTimeField(blank=True, help_text='Date et heure de lecture', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text="Date d'expiration de la notification", null=True)),
                ('recipient', models.ForeignKey(help_text='Utilisateur qui recevra la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx'), models.Index(fields=['priority'], name='notificatio_priorit_bf8ea0_idx')],
            },
        ),
    ]
