# Generated by Django 4.2.7 on 2025-06-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairecollecte',
            name='adresse_collecte',
            field=models.TextField(blank=True, help_text='Adresse où effectuer la collecte (obligatoire pour collecte à domicile)', null=True),
        ),
    ]
