# Generated by Django 5.2 on 2025-06-23 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_alter_formulairecollecte_adresse_collecte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formulairecollecte',
            name='date_validation',
            field=models.DateTimeField(blank=True, help_text='Date de validation/rejet', null=True),
        ),
        migrations.AddField(
            model_name='formulairecollecte',
            name='motif_rejet',
            field=models.TextField(blank=True, help_text='Motif du rejet si applicable', null=True),
        ),
        migrations.AddField(
            model_name='formulairecollecte',
            name='notes_admin',
            field=models.TextField(blank=True, help_text='Notes administratives', null=True),
        ),
        migrations.AddField(
            model_name='formulairecollecte',
            name='urgence',
            field=models.CharField(choices=[('faible', 'Faible'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', help_text="Niveau d'urgence de la demande", max_length=20),
        ),
        migrations.AddField(
            model_name='formulairecollecte',
            name='validateur',
            field=models.ForeignKey(blank=True, help_text='Administrateur qui a validé/rejeté', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulaires_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
