# Generated by Django 5.2 on 2025-06-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_address',
            field=models.TextField(blank=True, help_text="Adresse de l'entreprise (si applicable)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_phone',
            field=models.CharField(blank=True, help_text="Téléphone de l'entreprise (si applicable)", max_length=20, null=True),
        ),
    ]
